import { afterEach, describe, expect, it, vi } from 'vitest';
import beatmapInput from '@/content/beatmaps/office-day-01.json';
import { validateBeatmap } from '@/domain/validateBeatmap';
import { DEFAULT_AUDIO_SETTINGS, type AudioClockState } from '@/game/audio/types';
import { RhythmGameController } from '@/game/RhythmGameController';
import { SpaceInputController } from '@/game/input/SpaceInputController';
import { AutosaveCoordinator } from '@/game/persistence/AutosaveCoordinator';
import { createInitialRunState } from '@/game/state/reduceRunState';
import type { VerifiedInputEvent } from '@/server/cosmos/models';
import { validateRun } from './validateRun';

const beatmap = validateBeatmap(beatmapInput);

describe('live input persistence and verified replay', () => {
  afterEach(() => vi.useRealTimers());

  it('replays a full chart generated by SpaceInputController through autosave', async () => {
    const harness = createHarness();
    await harness.controller.start(0, harness.initialState);

    for (const event of beatmap.events) {
      if (event.type === 'tap') {
        harness.setSongPosition(event.startMs);
        harness.pressSpace();
        harness.setSongPosition(event.startMs + 10);
        harness.releaseSpace();
      } else if (event.type === 'hold') {
        harness.setSongPosition(event.startMs);
        harness.pressSpace();
        harness.setSongPosition(event.endMs!);
        harness.releaseSpace();
      } else {
        for (let press = 0; press < event.requiredPresses!; press += 1) {
          const position = event.startMs + Math.round(
            ((event.endMs! - event.startMs) * press) / Math.max(1, event.requiredPresses! - 1),
          );
          harness.setSongPosition(position);
          harness.pressSpace();
          harness.setSongPosition(position + 10);
          harness.releaseSpace();
        }
      }
    }

    const terminalState = harness.controller.getSnapshot().runState;
    expect(terminalState, JSON.stringify({
      nextEventIndex: terminalState.nextEventIndex,
      missCount: terminalState.missCount,
      lastJudgement: harness.controller.getSnapshot().lastJudgement,
      lastEvents: beatmap.events.slice(Math.max(0, terminalState.nextEventIndex - 2), terminalState.nextEventIndex + 2),
    })).toMatchObject({ status: 'completed' });
    const persistedEvents = await harness.flush();
    const validation = validateRun(beatmap, harness.initialState, toReplayEvents(persistedEvents), terminalState, 'completed');

    expect(validation).toMatchObject({ valid: true, state: terminalState });
    harness.dispose();
  });

  it('replays four automatic misses and a terminal late Space press with its release', async () => {
    const harness = createHarness();
    await harness.controller.start(0, harness.initialState);

    for (let index = 0; index < 4; index += 1) {
      const event = beatmap.events[index];
      const target = event.type === 'tap' ? event.startMs : event.endMs!;
      harness.setSongPosition(target + 161);
      harness.controller.update();
    }

    const finalEvent = beatmap.events[4];
    expect(finalEvent.type).toBe('tap');
    harness.setSongPosition(finalEvent.startMs + 161);
    harness.pressSpace();

    const terminalState = harness.controller.getSnapshot().runState;
    expect(terminalState).toMatchObject({ status: 'failed', hearts: 0, missCount: 5 });
    const persistedEvents = await harness.flush();
    const replayEvents = toReplayEvents(persistedEvents);
    const validation = validateRun(beatmap, harness.initialState, replayEvents, terminalState, 'failed');

    expect(persistedEvents.map((event) => event.type)).toEqual([
      'auto-miss', 'auto-miss', 'auto-miss', 'auto-miss', 'keydown', 'keyup',
    ]);
    expect(validation).toMatchObject({ valid: true, state: terminalState });
    harness.dispose();
  });
});

function createHarness() {
  const initialState = createInitialRunState({ runId: 'live-replay-run', userOid: 'live-replay-user', beatmapId: beatmap.id });
  let songPositionMs = 0;
  let clockState: AudioClockState = 'idle';
  const clock = {
    load: vi.fn(async () => undefined),
    start: vi.fn(async (position = 0) => { songPositionMs = position; clockState = 'playing'; }),
    pause: vi.fn(() => { clockState = 'paused'; }),
    resume: vi.fn(async () => { clockState = 'playing'; }),
    stop: vi.fn(() => { clockState = 'ended'; }),
    getSongPositionMs: vi.fn(() => songPositionMs),
    getState: vi.fn(() => clockState),
    setSettings: vi.fn(),
    subscribe: vi.fn(() => () => undefined),
  };
  const scheduler = {
    load: vi.fn(), start: vi.fn(), pause: vi.fn(), resume: vi.fn(), stop: vi.fn(),
    setFeverActive: vi.fn(), setSettings: vi.fn(), getMusicStatus: vi.fn(() => 'idle'),
  };
  const persistedEvents: VerifiedInputEvent[] = [];
  let version = 1;
  const controllerRef: { current?: RhythmGameController } = {};
  const api = {
    save: vi.fn(async (_runId: string, _version: string, events: VerifiedInputEvent[]) => {
      persistedEvents.push(...events);
      return { version: `v${++version}` };
    }),
  };
  const autosave = new AutosaveCoordinator({
    api: api as never,
    runId: initialState.runId,
    version: 'v1',
    readSnapshot: () => controllerRef.current!.getSnapshot().runState,
    options: { debounceMs: 60_000, intervalMs: 60_000 },
  });
  const inputTarget = new EventTarget();
  const input = new SpaceInputController({
    inputTarget,
    blurTarget: new EventTarget(),
    getGameState: () => controllerRef.current!.getSnapshot().runState.status === 'active'
      ? controllerRef.current!.getSnapshot().clockState
      : 'ended',
    getSongPositionMs: () => songPositionMs,
    initialSequence: 0,
    onPersistInput: (event) => autosave.recordInput(event),
    onInput: (event) => controllerRef.current!.handleInput(event),
    onPauseRequest: () => controllerRef.current!.pause(),
  });
  const controller = new RhythmGameController({
    beatmap,
    clock: clock as never,
    scheduler: scheduler as never,
    inputController: input,
    audioSettings: { ...DEFAULT_AUDIO_SETTINGS, muted: true },
    initialRunState: initialState,
  });
  controllerRef.current = controller;
  const unsubscribeMiss = controller.subscribeAutomaticMiss(({ chartEventId, songPositionMs: missPosition }) => {
    input.recordAutomaticMiss(chartEventId, missPosition);
  });

  return {
    controller,
    initialState,
    setSongPosition(position: number) { songPositionMs = position; },
    pressSpace() { dispatchSpace(inputTarget, 'keydown'); },
    releaseSpace() { dispatchSpace(inputTarget, 'keyup'); },
    async flush() {
      autosave.stop();
      await autosave.flush({ ...controller.getSnapshot().runState, status: 'active' });
      return persistedEvents;
    },
    dispose() { autosave.stop(); unsubscribeMiss(); controller.dispose(); },
  };
}

function dispatchSpace(target: EventTarget, type: 'keydown' | 'keyup'): void {
  const event = new Event(type, { cancelable: true });
  Object.defineProperty(event, 'code', { value: 'Space' });
  Object.defineProperty(event, 'repeat', { value: false });
  target.dispatchEvent(event);
}

function toReplayEvents(events: VerifiedInputEvent[]) {
  return events.map((event) => ({
    eventId: event.eventId,
    sequence: event.clientSequence,
    type: event.type,
    songPositionMs: event.songPositionMs,
    ...(event.type === 'auto-miss'
      ? { chartEventId: event.chartEventId }
      : { inputOffsetMs: event.inputOffsetMs }),
  }));
}
